# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a765473ab230ca5d15d216e99ce1f1415c99abd209a92e5ded7cf9e1e79634cf7f5cee9ffc6c490d6fb075c855f0fd95ae927e4918c25ec0360d6daf322d436d

test:
  secret_key_base: bb3a746ebee7627387bf801cba2ea9290bcc3d41fdbfecdf779491bd99652a576305ee32e77b59bba08e32e9c8d65724502f35323fc48a0f4555912609f7b1d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
